name: Tests and JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK-17
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    
    - name: Build
      run: ./gradlew build
      
    - name: Test
      run: ./gradlew test
    
    - name: Package
      run: ./gradlew assemble
    
    - name: Upload
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: |
          build/libs/
        retention-days: 30
